### PR TITLE
fix: bypassing sending a blank description (issue-38)

### LINKED ISSUE #38: Bypass sending item description if its blank
Passing along a blank description will cause the calling API endpoint to fail

### PR DESCRIPTION
**Pull request by brennan3**
fixes https://github.com/delphidigital/delphi-tg-bots/issues/38

### CODE REVIEW

File: bots/reads.ts [hunk 1]
```diff
@@ -304,6 +304,11 @@ const postRead = async (ctx: ReadsContext, config: ReadsConfig) => {
   const { delphiApi: { apiKey } } = config;
   const postReadsUrl = delphiApiUrl('/api/v1/bots/tg/create-read', config);
   const tg_username = ctx.callbackQuery.from.username;
+  const item = ctx.session.item;
```
Comment (stocks29) [inline bots/reads.ts]: thoughts on doing a deep copy here so we're not impacting the session state with changes to this var? there may be assumptions that some fields exist in there (now or in the future). one of those mutable language gotchas.

even this would be better, but it's not copying the nested arrays:

```ts
const item = { ...ctx.session.item };
```
